Repository ponylang/ponyup, pull requests merged in 2022-05, with the labels that each got.

#222 Update Linux SSL builder versions
  .github/workflows/breakage-against-linux-ponyc-latest.yml
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: discuss during sync

#223 Add PR checks on MacOS for Apple Silicon
  .ci-scripts/MacOS-arm64-install-pony-tools.bash
  .cirrus.yml
Labels: discuss during sync

#224 Add nightly builds for MacOS on Apple Silicon
  .ci-scripts/release/arm64-apple-darwin-nightly.bash
  .cirrus.yml
Labels: discuss during sync

#225 Update pony-init.sh to support arm64 targets
  ponyup-init.sh
Labels: do not merge

#226 Add ARM64 support
  .release-notes/arm64.md
  cmd/packages.pony
Labels: changelog - added

#227 Update crypto dependency
  corral.json
Labels: discuss during sync

#228 Add support for MacOS on Apple Silicon
  .ci-scripts/release/arm64-apple-darwin-release.bash
  .cirrus.yml
  .release-notes/arm64-macos.md
Labels: changelog - added, discuss during sync
